### ISSUE TITLE
XML Syntax Error: Please check the XML request to see if it can be parsed (Potentially Encoding)

### ISSUE THREAD

**Issue by MicahLyle** [Brobin/usps-api#6]
Using the address validate API with an address that has a city of `"Kapaʻa"` causes a returned error of `"XML Syntax Error: Please check the XML request to see if it can be parsed"`.

The developer guide (https://www.usps.com/business/web-tools-apis/general-api-developer-guide.htm) points out that "ISO-8859-1 encoding is the expected character set for the request". I manually tested making a request setting the `encoding='iso-8859-1'` in `etree`'s `tostring` and I initially thought that solved the problem, but then realized I had made a mistake and it didn't. Not sure at the moment why it's happening, or if it's just a USPS bug.

**Comment by Brobin** [comment]
Closed by #7
